version: '3.7'
services:
  frontend:
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  backend:
    build: ./backend
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
  generator01:
    build: ./generator01
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  generator02:
    build: ./generator02
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'flaskdb2'
  #     MYSQL_USER: 'me'
  #     MYSQL_PASSWORD: 'qwerty123'
  #   ports:
  #   - "306:3306"
  #   expose:
  #   - "3306"
    # volumes: 
    # - my-db:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf